### ISSUE TITLE
Cutting plane generation

### ISSUE THREAD

**Issue by andyYaoR** [grthor/Branch-and-Cut-for-a-DARP#1]
Hi Thorben,

I would like to know how did you generate cutting planes as described in the paper. I did not see it in your code, or maybe you handle it through cplex?

Best, Rui

**Comment by grthor** [comment]
Hi Rui, the code uses CPLEX's Presolve instead of cutting planes. 

In this presentation the difference between cutting planes and presolve is summarized https://resources.mpi-inf.mpg.de/conferences/adfocs-03/Slides/Rothberg_4.pdf

I can't tell you much about it, as I have only dealt with the subject superficially. My goal was only to implement restrictions 1 to 14 in CPLE .

Best regards
Thorben

**Comment by andyYaoR** [comment]
Thank you very much!
Rui
