### ISSUE TITLE
replicate results

### ISSUE THREAD

**Issue by andyYaoR** [grthor/Branch-and-Cut-for-a-DARP#2]
Hi Thorben,

Are you able to replicate the solutions obtained from Cordeau (2006)? In my case, the algorithm returns no solution exists. 

benchmark instances:
http://neumann.hec.ca/chairedistributique/data/darp/branch-and-cut/

Best, Rui

**Comment by grthor** [comment]
Hi Rui, 

So far I have not tried to reproduce the results. But I can try to do so in the next few days.

As soon as I have the results I will let you know.

Best regards
Thorben

**Comment by andyYaoR** [comment]
Thank you!

**Comment by grthor** [comment]
Hi, Rui, 

i was able to reproduce the results, at least for the first set with 2 trucks and 16 pick-up nodes. I think the others should work too.

The problem was that my knots were not in a graph with x values from -10 to 10 and y values from -10 to 10, as in Cordeau's graph, but geographic positions (cities in North Rhine-Westphalia (a federal state in Germany)). To make the travel times t realistic I multiplied the distance c by 15. In Cordeau's case t is equal to c (This is stated in Cordeau's paper p.17 under "Computational Experiments").

With t equal to c it works. I just changed that and pushed it. Here you can see the line where t is calculated https://github.com/grthor/Branch-and-Cut-for-a-DARP/blob/c94660fbd9dcf204b2cf7a7a373846516076da3a/src/logic/model.java#L91

Hopefully you will get further now
Thorben

**Comment by andyYaoR** [comment]
Hi Thorben,
 
Thank you for the update. The code now works. Maybe we should explain the parameter settings in the readme file. 

Best, Rui

**Comment by grthor** [comment]
Hi Rui,

feel free to change the readme fiel.

You can edit it directly in your browser. After you have finished GitHub creates a PR and I can merge it.

Greetings
Thorben

Von: Rui Yao <notifications@github.com>
Gesendet: Mittwoch, 4. März 2020 19:58
An: grthor/Branch-and-Cut-for-a-DARP <Branch-and-Cut-for-a-DARP@noreply.github.com>
Cc: Groos, Thorben <thorben.groos@student.uni-siegen.de>; Comment <comment@noreply.github.com>
Betreff: Re: [grthor/Branch-and-Cut-for-a-DARP] replicate results (#2)


Hi Thorben,

Thank you for the update. The code now works. Maybe we should explain the parameter settings in the readme file.

Best, Rui
